### ISSUE TITLE
[Feature] Current streak and max streak

### ISSUE THREAD

**Issue by AnderRasoVazquez** [lordi/tickmate#66] opened 2016-02-15 17:25 UTC
I really like Tickmate, I was searching an app on F-droid similar to [Rewire](https://play.google.com/store/apps/details?id=com.rstudioz.habits) to track my habits and open source, when I found it =). I think Tickmate's "bit user interface" is more convenient than Rewire's multiple calendar interface. 

The only thing I miss from Rewire would be to **know how many days I've been doing something right consecutively, since the last time I failed** (that would be the current streak). And of course, what was the longest streak (max number of days clicking and habit and not failing it, a high score).

Keep up the good work! ^^

**Comment by lordi** [comment] 2016-02-18 12:27
Thanks, I will consider it for next release!
I will close this issue as it is a duplicate of #32

**Closed by lordi** 2016-02-18 12:27 UTC
