### ISSUE TITLE
Edit protection for multiple ticks

### ISSUE THREAD

**Issue by andunix** [lordi/tickmate#60] opened 2016-01-11 08:28 UTC
I have activated "edit only today and yesterday". For normal tracks, it works, but for multitick-tracks, I can edit also older days.

**Comment by lordi** [comment] 2016-01-11 21:41
Hi, thanks for the bug report. It is a duplicate of #52. The issue is fixed in `master` and will be released within the next weeks

**Closed by lordi** 2016-01-11 21:41 UTC
