### ISSUE TITLE
The longest streak.

### ISSUE THREAD

**Issue by rozie** [lordi/tickmate#83] opened 2016-08-07 05:13 UTC
There's already option _days since last_, I guess _the longest streak_ showing the highest value how many days in a row given tick was given would be useful too and easy to implement.

**Comment by lordi** [comment] 2016-08-07 14:40
Duplicate of #32 

I implemented this, but I didn't release a new version that includes the changes yet. I'll try to release it within the next week or so.

**Closed by lordi** 2016-08-07 14:40 UTC
